### ISSUE TITLE
Manually removing the background on GIMP produces better results

### ISSUE THREAD

**Issue by gabrielwoj** [Lexzach/hlmv-transparent#1] opened 2021-01-26 11:05 UTC
I decided to test how the image would look when manually removing the background via GIMP (with the process explained on the Help:Cosmetic Images page on the Wiki), and the anti-alias is much better produced than the one with the program.

The first image "1.png", is a difference between an image manipulated on GIMP vs. an image made with your program. Notice how the colored pixels are all focused on the edges of the cigar.

![1](https://user-images.githubusercontent.com/13741779/105837133-0272f000-5fad-11eb-8ee5-ff771283c4eb.png)

The most notable part is probably Spy's arm. "2.png" is part of the image manipulated by hlmv-transparent, while "3.png" was the same image, but removed manually using GIMP. You can see the lack of anti-alias with the "blocky" black pixels around the image, where as in "3.png", it's smooth.

![2](https://user-images.githubusercontent.com/13741779/105837137-030b8680-5fad-11eb-937c-4f0c9ffd5b33.png)
![3](https://user-images.githubusercontent.com/13741779/105837138-030b8680-5fad-11eb-9a12-851dc276e43d.png)

I know it sucks manually removing the background for each image on the Wiki using GIMP, but for now, it produces higher quality images.

Not sure if you know this, but in GIMP, a better quality image can be made if the white background layer is on the bottom layer and the black background layer is on the top layer (see "4.png").

![4](https://user-images.githubusercontent.com/13741779/105837139-03a41d00-5fad-11eb-9823-0b3893e61d27.png)

Doing that, the anti-alias effect will apply to the black background one. Doing reverse will cause the anti-alias to use the white pixels, and the image won't look very good if used on a dark background.

**Comment by Lexzach** [comment] 2021-01-27 03:11
~~I have added the `pixelLenience` to confix.txt, this allows for less jagged edges, and essentially Anti-Aliasing. Maybe try that out and see how that works?~~
Edit: I updated the program to be compatible with gpu anti-aliasing. I would advise keeping `pixelLenience` on 3 right now.

**Comment by Lexzach** [comment] 2021-01-27 22:36
Okay I have released an update. That black line was actually caused by a bug with the line numbers. It should be fixed now. Please try again and let me know how it works! 👍

**Comment by Lexzach** [comment] 2021-01-28 02:43
Final update: I have been hard at work all day, and it seems all rendering issues have been completely resolved, please try version 2.0 to see how it performs!

**Closed as completed** 2021-01-28 14:57 UTC
